name: "Nightly Build & DockerHub Deployment"

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:  

jobs:
  test_phase:
    name: "Execute Unit Tests"
    runs-on: ubuntu-latest
    environment: "Production Secrets"
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v4

      - name: "Set Up Python Environment"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Install Project Dependencies"
        run: python -m pip install -r requirements.txt

      - name: "Debug: Show Python Info and Installed Packages"
        run: |
          echo "Python location: $(which python)"
          python --version
          echo "Installed packages:"
          python -m pip list
          echo "Attempting to import pytest:"
          python -c "import pytest; print('pytest version:', pytest.__version__)"

      - name: "Run Test Suite"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
          DOMAIN: ${{ secrets.DOMAIN }}
        run: python -m pytest

      - name: "Alert on Test Failures"
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Nightly Build Alert: Test Failures Detected"
          to: "ssshaikh7@dons.usfca.edu"
          from: "${{ secrets.MAIL_FROM_NAME }} <${{ secrets.MAIL_FROM }}>"
          body: "Automated tests did not pass during the nightly build. Please check the build logs."

  deploy_phase:
    name: "Build & Push Docker Images"
    needs: test_phase
    runs-on: ubuntu-latest
    environment: "Production Secrets"
    steps:
      - name: "Retrieve Latest Code"
        uses: actions/checkout@v4

      - name: "Authenticate with DockerHub"
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: "Build & Tag Web Service Image"
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-web:nightly -f Dockerfile .
          docker images

      - name: "Push Web Service Image"
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-web:nightly || { echo "Docker push failed!"; exit 1; }

      - name: "Build & Tag Celery Service Image"
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-celery:nightly -f Dockerfile .
          docker images

      - name: "Push Celery Service Image"
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-celery:nightly || { echo "Docker push failed!"; exit 1; }

      - name: "Notify if Docker Push Fails"
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Nightly Build: Docker Image Deployment Issue"
          to: "ssshaikh7@dons.usfca.edu"
          from: "${{ secrets.MAIL_FROM_NAME }} <${{ secrets.MAIL_FROM }}>"
          body: "One or more Docker images failed to push during the nightly build. Please review the logs for details."

      - name: "Notify on Successful Deployment"
        if: success()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Nightly Build: Docker Image Deployment Successful"
          to: "ssshaikh7@dons.usfca.edu"
          from: "${{ secrets.MAIL_FROM_NAME }} <${{ secrets.MAIL_FROM }}>"
          body: "The nightly build completed successfully, and all Docker images were built and pushed to DockerHub."
